services:
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    dockerContext: ./nginx
    plan: free
    autoDeploy: false
    envVars:
      - key: CLIENT_URL
        value: https://client-vxpx.onrender.com
      - key: API_URL
        value: https://api-7x97.onrender.com
  - type: web
    name: client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    autoDeploy: false
    envVars:
      - key: API_URL
        value: https://api-7x97.onrender.com
  - type: web
    name: api
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    autoDeploy: false
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          type: redis
          property: port
      - key: PGHOST
        fromDatabase:
          name: app-postgres
          property: host
      - key: PGUSER
        fromDatabase:
          name: app-postgres
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: app-postgres
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: app-postgres
          property: database
      - key: PGPORT
        fromDatabase:
          name: app-postgres
          property: port
  - type: redis
    name: redis
    plan: free
    ipAllowList: []

databases:
  - name: app-postgres
    databaseName: fib_calc
    user: fib_user
    plan: free
