services:
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    dockerContext: ./nginx
    plan: free
    autoDeploy: false
    envVars:
      - key: API_URL
        fromService:
          name: api
          type: web
          property: url
      - key: CLIENT_URL
        fromService:
          name: client
          type: web
          property: url
  - type: web
    name: client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    autoDeploy: false
  - type: web
    name: api
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    autoDeploy: false
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          type: redis
          property: port
      - key: PGHOST
        fromDatabase:
          name: app-postgres
          property: host
      - key: PGUSER
        fromDatabase:
          name: app-postgres
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: app-postgres
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: app-postgres
          property: database
      - key: PGPORT
        fromDatabase:
          name: app-postgres
          property: port
  - type: worker
    name: worker
    env: docker
    dockerfilePath: ./worker/Dockerfile
    dockerContext: ./worker
    plan: free
    autoDeploy: false
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          type: redis
          property: port
  - type: redis
    name: redis
    plan: free
    ipAllowList: []

databases:
  - name: app-postgres
    databaseName: fib_calc
    user: fib_user
    plan: free
